# All the libraries you may need to use the forecasting functions
library(data.table)
library(dplyr)
library(forecast)
library(ggplot2)
library(gridExtra)
library(lemon)
library(lubridate)
library(timeDate)
library(writexl)
library(zoo)
library(viridis)
library(RColorBrewer)